-- ADVERTENCIA: Las contraseñas de los usuarios de prueba están en texto plano. NO USAR EN PRODUCCIÓN.

-- Borra datos existentes para evitar duplicados --
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Transactions;
TRUNCATE TABLE Stores;
TRUNCATE TABLE Routes;
-- No borramos los usuarios existentes, solo añadimos los de prueba
DELETE FROM Users WHERE id IN (1, 2);
SET FOREIGN_KEY_CHECKS = 1;

-- Datos de prueba para la tabla Users
INSERT INTO Users (id, nombre, email, password, rol, createdAt, updatedAt) VALUES (1, 'Ciclista de Prueba', 'ciclista@prueba.com', 'password123', 'Ciclista', NOW(), NOW());
INSERT INTO Users (id, nombre, email, password, rol, createdAt, updatedAt) VALUES (2, 'Creador de Rutas de Prueba', 'creador@prueba.com', 'password123', 'Creador de Ruta', NOW(), NOW());

-- Datos de prueba para la tabla Routes
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #1', 'Descripción de prueba para la ruta #1', 30.54, 'Fácil', 16.36, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #2', 'Descripción de prueba para la ruta #2', 27.16, 'Fácil', 23.83, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #3', 'Descripción de prueba para la ruta #3', 20.54, 'Difícil', 22.25, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #4', 'Descripción de prueba para la ruta #4', 16.79, 'Intermedia', 7.38, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #5', 'Descripción de prueba para la ruta #5', 7.4, 'Difícil', 17.21, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #6', 'Descripción de prueba para la ruta #6', 17.06, 'Fácil', 17.03, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #7', 'Descripción de prueba para la ruta #7', 41.27, 'Fácil', 13.37, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #8', 'Descripción de prueba para la ruta #8', 38.05, 'Fácil', 6.97, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #9', 'Descripción de prueba para la ruta #9', 15.34, 'Difícil', 16.05, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #10', 'Descripción de prueba para la ruta #10', 20.46, 'Fácil', 14.72, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #11', 'Descripción de prueba para la ruta #11', 9.38, 'Difícil', 8.24, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #12', 'Descripción de prueba para la ruta #12', 45.23, 'Intermedia', 15.61, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #13', 'Descripción de prueba para la ruta #13', 29.59, 'Difícil', 21.56, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Circuito del Lago #14', 'Descripción de prueba para la ruta #14', 48.99, 'Difícil', 23.9, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #15', 'Descripción de prueba para la ruta #15', 7.66, 'Difícil', 14.98, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #16', 'Descripción de prueba para la ruta #16', 29.34, 'Fácil', 18.25, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #17', 'Descripción de prueba para la ruta #17', 15.88, 'Fácil', 21.64, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Circuito del Lago #18', 'Descripción de prueba para la ruta #18', 20.57, 'Fácil', 13.54, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #19', 'Descripción de prueba para la ruta #19', 11.4, 'Difícil', 21.27, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #20', 'Descripción de prueba para la ruta #20', 14.0, 'Intermedia', 16.54, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #21', 'Descripción de prueba para la ruta #21', 9.1, 'Difícil', 23.41, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #22', 'Descripción de prueba para la ruta #22', 48.98, 'Fácil', 19.96, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #23', 'Descripción de prueba para la ruta #23', 10.02, 'Difícil', 9.27, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #24', 'Descripción de prueba para la ruta #24', 25.21, 'Difícil', 17.26, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #25', 'Descripción de prueba para la ruta #25', 18.84, 'Fácil', 11.43, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #26', 'Descripción de prueba para la ruta #26', 37.21, 'Fácil', 21.39, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #27', 'Descripción de prueba para la ruta #27', 39.29, 'Fácil', 22.09, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #28', 'Descripción de prueba para la ruta #28', 28.33, 'Difícil', 12.45, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #29', 'Descripción de prueba para la ruta #29', 25.55, 'Fácil', 19.76, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #30', 'Descripción de prueba para la ruta #30', 31.06, 'Fácil', 15.81, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #31', 'Descripción de prueba para la ruta #31', 31.56, 'Intermedia', 12.39, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #32', 'Descripción de prueba para la ruta #32', 18.12, 'Difícil', 12.89, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Circuito del Lago #33', 'Descripción de prueba para la ruta #33', 22.04, 'Intermedia', 8.79, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #34', 'Descripción de prueba para la ruta #34', 38.29, 'Difícil', 7.24, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Circuito del Lago #35', 'Descripción de prueba para la ruta #35', 24.21, 'Fácil', 12.68, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #36', 'Descripción de prueba para la ruta #36', 6.0, 'Intermedia', 18.97, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #37', 'Descripción de prueba para la ruta #37', 9.3, 'Difícil', 9.92, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Senda del Bosque #38', 'Descripción de prueba para la ruta #38', 17.31, 'Fácil', 22.69, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #39', 'Descripción de prueba para la ruta #39', 32.05, 'Fácil', 9.83, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #40', 'Descripción de prueba para la ruta #40', 23.98, 'Difícil', 17.1, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #41', 'Descripción de prueba para la ruta #41', 45.82, 'Difícil', 6.7, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #42', 'Descripción de prueba para la ruta #42', 30.34, 'Fácil', 9.61, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #43', 'Descripción de prueba para la ruta #43', 28.88, 'Difícil', 5.12, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Ruta del Sol #44', 'Descripción de prueba para la ruta #44', 29.45, 'Intermedia', 14.76, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #45', 'Descripción de prueba para la ruta #45', 10.2, 'Intermedia', 15.38, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Paseo de las Montañas #46', 'Descripción de prueba para la ruta #46', 5.54, 'Fácil', 17.91, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #47', 'Descripción de prueba para la ruta #47', 6.29, 'Difícil', 12.19, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Circuito del Lago #48', 'Descripción de prueba para la ruta #48', 5.79, 'Fácil', 10.84, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Camino de la Luna #49', 'Descripción de prueba para la ruta #49', 43.19, 'Difícil', 6.43, 2, 'aprobada', NOW(), NOW());
INSERT INTO Routes (nombre, descripcion, distancia, dificultad, precio, creadorId, estado, createdAt, updatedAt) VALUES ('Circuito del Lago #50', 'Descripción de prueba para la ruta #50', 45.21, 'Intermedia', 24.93, 2, 'aprobada', NOW(), NOW());

-- Datos de prueba para la tabla Stores
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #1', 'Descripción de prueba para el comercio #1', 'Ubicación de prueba #1', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #2', 'Descripción de prueba para el comercio #2', 'Ubicación de prueba #2', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #3', 'Descripción de prueba para el comercio #3', 'Ubicación de prueba #3', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #4', 'Descripción de prueba para el comercio #4', 'Ubicación de prueba #4', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #5', 'Descripción de prueba para el comercio #5', 'Ubicación de prueba #5', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #6', 'Descripción de prueba para el comercio #6', 'Ubicación de prueba #6', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #7', 'Descripción de prueba para el comercio #7', 'Ubicación de prueba #7', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #8', 'Descripción de prueba para el comercio #8', 'Ubicación de prueba #8', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #9', 'Descripción de prueba para el comercio #9', 'Ubicación de prueba #9', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #10', 'Descripción de prueba para el comercio #10', 'Ubicación de prueba #10', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #11', 'Descripción de prueba para el comercio #11', 'Ubicación de prueba #11', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #12', 'Descripción de prueba para el comercio #12', 'Ubicación de prueba #12', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #13', 'Descripción de prueba para el comercio #13', 'Ubicación de prueba #13', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #14', 'Descripción de prueba para el comercio #14', 'Ubicación de prueba #14', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #15', 'Descripción de prueba para el comercio #15', 'Ubicación de prueba #15', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #16', 'Descripción de prueba para el comercio #16', 'Ubicación de prueba #16', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #17', 'Descripción de prueba para el comercio #17', 'Ubicación de prueba #17', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #18', 'Descripción de prueba para el comercio #18', 'Ubicación de prueba #18', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #19', 'Descripción de prueba para el comercio #19', 'Ubicación de prueba #19', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #20', 'Descripción de prueba para el comercio #20', 'Ubicación de prueba #20', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #21', 'Descripción de prueba para el comercio #21', 'Ubicación de prueba #21', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #22', 'Descripción de prueba para el comercio #22', 'Ubicación de prueba #22', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #23', 'Descripción de prueba para el comercio #23', 'Ubicación de prueba #23', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #24', 'Descripción de prueba para el comercio #24', 'Ubicación de prueba #24', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #25', 'Descripción de prueba para el comercio #25', 'Ubicación de prueba #25', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #26', 'Descripción de prueba para el comercio #26', 'Ubicación de prueba #26', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #27', 'Descripción de prueba para el comercio #27', 'Ubicación de prueba #27', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #28', 'Descripción de prueba para el comercio #28', 'Ubicación de prueba #28', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #29', 'Descripción de prueba para el comercio #29', 'Ubicación de prueba #29', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #30', 'Descripción de prueba para el comercio #30', 'Ubicación de prueba #30', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #31', 'Descripción de prueba para el comercio #31', 'Ubicación de prueba #31', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #32', 'Descripción de prueba para el comercio #32', 'Ubicación de prueba #32', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #33', 'Descripción de prueba para el comercio #33', 'Ubicación de prueba #33', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #34', 'Descripción de prueba para el comercio #34', 'Ubicación de prueba #34', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #35', 'Descripción de prueba para el comercio #35', 'Ubicación de prueba #35', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #36', 'Descripción de prueba para el comercio #36', 'Ubicación de prueba #36', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #37', 'Descripción de prueba para el comercio #37', 'Ubicación de prueba #37', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #38', 'Descripción de prueba para el comercio #38', 'Ubicación de prueba #38', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #39', 'Descripción de prueba para el comercio #39', 'Ubicación de prueba #39', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #40', 'Descripción de prueba para el comercio #40', 'Ubicación de prueba #40', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #41', 'Descripción de prueba para el comercio #41', 'Ubicación de prueba #41', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Tienda de Artesanías #42', 'Descripción de prueba para el comercio #42', 'Ubicación de prueba #42', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #43', 'Descripción de prueba para el comercio #43', 'Ubicación de prueba #43', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #44', 'Descripción de prueba para el comercio #44', 'Ubicación de prueba #44', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #45', 'Descripción de prueba para el comercio #45', 'Ubicación de prueba #45', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('La Esquina del Sabor #46', 'Descripción de prueba para el comercio #46', 'Ubicación de prueba #46', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Mercado del Pueblo #47', 'Descripción de prueba para el comercio #47', 'Ubicación de prueba #47', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #48', 'Descripción de prueba para el comercio #48', 'Ubicación de prueba #48', 3, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Bici-Repuestos Express #49', 'Descripción de prueba para el comercio #49', 'Ubicación de prueba #49', 4, 'activo', NOW(), NOW());
INSERT INTO Stores (nombre, descripcion, ubicacion, propietarioId, estado, createdAt, updatedAt) VALUES ('Café del Sendero #50', 'Descripción de prueba para el comercio #50', 'Ubicación de prueba #50', 3, 'activo', NOW(), NOW());

-- Datos de prueba para la tabla Transactions
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (34.44, 'compra_ruta', 1, 30, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (83.88, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (82.63, 'compra_ruta', 1, 40, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (85.58, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (13.87, 'compra_ruta', 1, 13, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (24.73, 'compra_ruta', 1, 14, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (18.0, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (30.92, 'compra_ruta', 1, 45, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (16.94, 'compra_ruta', 1, 49, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (48.11, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (99.1, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (64.14, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (55.71, 'compra_ruta', 1, 27, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (70.9, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (22.89, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (72.73, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (77.01, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (17.11, 'compra_ruta', 1, 43, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (89.82, 'compra_ruta', 1, 5, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (10.18, 'compra_ruta', 1, 38, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (36.51, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (19.65, 'compra_ruta', 1, 21, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (45.72, 'compra_ruta', 1, 20, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (95.48, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (65.7, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (35.71, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (31.34, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (39.54, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (19.71, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (27.58, 'compra_ruta', 1, 19, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (91.31, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (31.92, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (12.76, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (90.4, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (78.43, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (42.97, 'compra_ruta', 1, 2, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (70.35, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (77.89, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (77.9, 'compra_ruta', 1, 14, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (18.33, 'compra_ruta', 1, 9, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (36.26, 'compra_ruta', 1, 16, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (29.56, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (43.57, 'compra_ruta', 1, 24, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (41.92, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (10.42, 'compra_ruta', 1, 1, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (11.13, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (18.49, 'compra_ruta', 1, 20, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (30.59, 'compra_ruta', 1, 50, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (35.94, 'pedido_comercio', 1, NULL, NOW(), NOW());
INSERT INTO Transactions (monto, tipo, usuarioId, rutaId, createdAt, updatedAt) VALUES (91.07, 'compra_ruta', 1, 1, NOW(), NOW());
